### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by danielnjoo** [mruoss/jquery-scroll-indicator-bullets#3]
Hi! I loved your demo, and was trying to add this to my website. I have all the resources loaded, but can't figure out the script you actually used in your demo.

For example in my website I have the following HTML structure:

```
<section id="1"/>
<section id="2"/>
<section id="3"/>

```
and in my head I have a 

```
<script type="text/javascript">
   $('section.1').scrollIndicatorBullets();
   $('section.2).scrollIndicatorBullets();
   $('section.3').scrollIndicatorBullets();
</script>
```

And have also tried

```
(function ($) {
      $(function () {
        $('.section').scrollIndicatorBullets({
      titleSelector: 'h1,h2,h3'
    });
})(jQuery);
```

Advice appreciated!

**Comment by mruoss** [comment]
Hi  @danielnjoo 

For the demo I'm using github pages - you can find the used script on the branch [`gh-pages`](https://github.com/mruoss/jquery-scroll-indicator-bullets/tree/gh-pages) of this project's repository.

Looking at your approaches though, I can see a couple of problems. Generally, dots in jquery selectors stand for classes. `$('section.1')` would therefore match `<section class="1"/>`, in order to match id's, use a hash (`$('#1')`).
Same problem in the second approach, `$('.section')` matches `class="section"`.

Have a look at my demo script and the HTML of the demo. I'm using elements as follows: `<div id="usage-section" class="scroll-section">` and select them them using `$(.scroll-section)`.

**Comment by danielnjoo** [comment]
Hey thanks for the reply, didn't get to try it till now, but I can't seem to get it to work still :(. 

```
<section class ="about page-section"/>
<section class="faq page-section"/>
<section class="sponsor page-section"/>
```

then in the head

```
<link rel="stylesheet" type="text/css" href="https://cdn.rawgit.com/mruoss/jquery-scroll-indicator-bullets/2.0.0/dist/jquery.scrollindicatorbullets.css" media="screen">
<script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.js"></script>
  <script src="https://cdn.rawgit.com/imakewebthings/waypoints/4.0.0/lib/noframework.waypoints.min.js"></script>
  <script src="https://cdn.rawgit.com/mruoss/jquery-scroll-indicator-bullets/2.0.0/dist/jquery.scrollindicatorbullets.min.js"></script>
<script type="text/javascript">
  (function ($) {
    $(function () {
      $('.page-section').scrollIndicatorBullets({
         titleSelector: 'h1,h2,h3'
      });
    });
  })(jQuery);
  </script>
```

I don't see any problems in the inspector with resource loading, but I don't see the indicators. However, scroll doesn't work at all anymore which I guess means something is happening? 

Thanks!

**Comment by danielnjoo** [comment]
Note scroll only stops working when I load modernizr.js

**Comment by mruoss** [comment]
You might want to set it up in a [JSBIN](https://jsbin.com) to illustrate.
